dataset: "semantic_kitti"
save_dir: "ConvBKI_PerClass_Compound_semantic_kitti"
load_epoch: 0
map_method: "global"
visualize: True
train:
  B: 16
  num_epochs: 5
  lr: 0.007
  BETA1: 0.9
  BETA2: 0.999
  decayRate: 0.96
  remove_last: True
  opt: "SGD"
  grid_params:
    grid_size: [256.0, 256.0, 32.0]
    min_bound: [-12.8, -12.8, -2.6]
    max_bound: [12.8, 12.8, 0.6]
test:
  grid_params:
    grid_size: [513.0, 513.0, 17.0] #[512.0, 512.0, 32.0]
    min_bound: [-25.6, -25.6, -2.0]
    max_bound: [25.6, 25.6, 1.2]
filter_size: 15
kernel: "sparse"
compound: True
per_class: True
ell: 0.3
seed: 42

num_frames: 16
num_workers: 16

debug_mode: False