dataset: "kitti_odometry"
save_dir: "ConvBKI_kitti_odometry_perclass"
load_epoch: 3
map_method: "global"
visualize: False
meas_result: True
gen_preds: False
result_split: "test"
from_continuous: False
to_continuous: False
pred_path: "predictions_darknet"
train:
  B: 4
  num_epochs: 10 
  lr: 0.007
  BETA1: 0.9 
  BETA2: 0.999
  decayRate: 0.96
  remove_last: False
  opt: "Adam" 
  grid_params:
    grid_size: [800.0, 800.0, 50.0]
    min_bound: [-40.0, -40.0, -2.5] #[-40.0, -40.0, -2.65]
    max_bound: [40.0, 40.0, 2.5] #[40.0, 40.0, 3.75]
test:
  grid_params:
    grid_size: [801.0, 801.0, 51.0] #[512.0, 512.0, 32.0]
    min_bound: [-40.05, -40.05, -2.55]
    max_bound: [40.05, 40.05, 2.55]
filter_size: 9
kernel: "sparse"
compound: False
per_class: True
ell: 0.5
seed: 42

num_frames: 10
num_workers: 16

debug_mode: False